name: Build, Test & Release 🧪🚀
on:
  push:
concurrency: ci-${{ github.ref}}-${{ github.event_name }}
jobs:
  build-and-test:
    if: github.ref_name == github.event.repository.default_branch && !contains( github.event.head_commit.message, 'skip ci' )
    uses: ./.github/workflows/build-test-common.yml
    secrets: inherit
    with:
      actor: ${{ github.actor }}
      ref: ${{ github.ref }}
      is_main_branch: true
      commit: ${{ github.sha }}
  trigger-deploy-dev:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch && !contains( github.event.head_commit.message, 'skip-ci' )
    timeout-minutes: 5
    steps:
      - name: trigger deployment
        run: |
          gh api --method POST repos/${{ github.repository }}/deployments -f ref=${{ github.sha }} -f environment=dev -f description="Deploy ref ${{ github.sha }} to def" -f required_contexts=false
